#' Summarize Coding Potential Results for Test Sets
#'
#' Filters and annotates coding potential results from `codPotToTbl` based on
#' provided non-coding and coding test sets. It calculates the sum of
#' non-coding predictions across tools for the filtered sequences.
#'
#' @param codPotList A list object generated by `codPotToTbl()`. Must contain
#'   `$seqIDs` and `$tools` (a named list of 0/1 prediction vectors).
#' @param ncTest A character vector of sequence IDs known to be non-coding.
#' @param cdsTest A character vector of sequence IDs known to be protein-coding.
#'
#' @return A list containing elements for sequences present in `ncTest` or
#'   `cdsTest`:
#'   \item{seqIDs}{Filtered character vector of sequence identifiers.}
#'   \item{tools}{Filtered list of tool prediction vectors.}
#'   \item{type}{Filtered character vector with annotation ("nc" or "cds").}
#'   \item{isNC}{Filtered numeric vector: 1 for "nc", 0 for "cds".}
#'   \item{sums}{Filtered numeric vector with the sum of predictions across all
#'     tools.}
#'
#' @keywords summary validation lncRNA cds filter
#' @export
#' @examples
#' # --- 1. Create a mock object that mimics the output of codPotToTbl ---
#' mockCodPot <- list(
#'   seqIDs = c("ID1", "ID2", "ID3", "ID4", "ID5"),
#'   tools = list(
#'     CPC2 = c(1, 1, 0, 0, 1),
#'     PLEK = c(0, 1, 1, 0, 1)
#'   )
#' )
#'
#' # --- 2. Define test sets ---
#' ncTestSet <- c("ID1", "ID2", "ID5")
#' cdsTestSet <- c("ID3")
#' # Note: ID4 is not in any test set and will be filtered out.
#'
#' # --- 3. Run the function ---
#' summaryList <- sumSingleTools(
#'   codPotList = mockCodPot,
#'   ncTest = ncTestSet,
#'   cdsTest = cdsTestSet
#' )
#'
#' print(summaryList)
#'
sumSingleTools <- function(codPotList, ncTest, cdsTest) {
  # --- 1. Input Validation ---
  stopifnot(
    "'codPotList' must be a list with 'seqIDs' and 'tools' elements" =
      (is.list(codPotList) && all(c("seqIDs", "tools") %in% names(codPotList))),
    "'codPotList$tools' must be a list" = is.list(codPotList$tools),
    "'ncTest' must be a character vector" = is.character(ncTest),
    "'cdsTest' must be a character vector" = is.character(cdsTest)
  )

  # --- 2. Identify and Filter Sequences ---
  originalSeqIDs <- codPotList$seqIDs
  testSetIDs <- union(ncTest, cdsTest)

  # Find indices of sequences that are in our test sets
  indicesToKeep <- which(originalSeqIDs %in% testSetIDs)

  if (length(indicesToKeep) == 0) {
    warning("None of the sequences in 'codPotList' were found in the test sets.")
    return(list(seqIDs = character(0), tools = list(), type = character(0),
                isNC = numeric(0), sums = numeric(0)))
  }

  filteredSeqIDs <- originalSeqIDs[indicesToKeep]

  # --- 3. Filter Tool Predictions (Efficiently) ---
  filteredTools <- lapply(codPotList$tools, function(toolVector) {
    if (length(toolVector) != length(originalSeqIDs)) {
      warning("Length mismatch for tool. Returning NULLs for this tool.", call. = FALSE)
      return(rep(NA_integer_, length(indicesToKeep)))
    }
    toolVector[indicesToKeep]
  })

  # --- 4. Create Annotations for Filtered Data ---
  nFiltered <- length(filteredSeqIDs)
  filteredType <- character(nFiltered)

  # Assign type based on which test set the ID belongs to.
  # ncTest takes precedence if an ID is in both.
  filteredType[filteredSeqIDs %in% cdsTest] <- "cds"
  filteredType[filteredSeqIDs %in% ncTest] <- "nc"

  filteredIsNC <- ifelse(filteredType == "nc", 1, 0)

  # --- 5. Calculate Sums for Filtered Data ---
  if (length(filteredTools) > 0) {
    filteredToolMatrix <- do.call(cbind, filteredTools)
    filteredSums <- rowSums(filteredToolMatrix, na.rm = TRUE)
  } else {
    warning("'codPotList' contains no tool predictions. Sums will be 0.")
    filteredSums <- numeric(nFiltered)
  }

  # --- 6. Assemble the Final List ---
  resultList <- list(
    seqIDs = filteredSeqIDs,
    tools = filteredTools,
    type = filteredType,
    isNC = filteredIsNC,
    sums = filteredSums
  )

  return(resultList)
}
