#' Evaluate Agreement Thresholds Among Coding Potential Tools
#'
#' Calculates agreement statistics for a selection of coding potential tools.
#' For each sequence, it determines if it was predicted as non-coding by at
#' least 'n' of the selected tools, for all possible values of 'n'.
#'
#' @param summaryList A list generated by `summarizeTestSet()`, containing
#'   `$seqIDs`, `$tools`, `$isNC`, and `$type`.
#' @param tools An optional character vector specifying which tools to include
#'   in the agreement analysis. If `NULL`, the behavior depends on the session:
#'   interactive mode will prompt for selection, while non-interactive mode
#'   will use all available tools.
#'
#' @return A list containing:
#'   \item{seqIDs}{Original sequence identifiers from the input.}
#'   \item{isNC}{Original true labels (1=nc, 0=cds) from the input.}
#'   \item{type}{Original type annotation ('nc', 'cds') from the input.}
#'   \item{selectedToolsPredictions}{A list containing only the prediction
#'     vectors for the tools that were selected for analysis.}
#'   \item{sumsSelectedTools}{An integer vector with the count of selected
#'     tools that predicted "non-coding" (1) for each sequence.}
#'   \item{atLeastN}{A list where each element `atl{n}` is a binary
#'     vector indicating if a sequence was predicted as non-coding by at least
#'     `n` selected tools. This list contains all threshold sets.}
#' @export
#'
#' @examples
#' # --- 1. Create Example Data (mimicking summarizeTestSet output) ---
#' set.seed(456)
#' n_seq <- 50
#' exampleSummaryList <- list(
#'   seqIDs = paste0("ID", 1:n_seq),
#'   tools = list(
#'     ToolA = sample(c(0, 1), n_seq, replace = TRUE),
#'     ToolB = sample(c(0, 1), n_seq, replace = TRUE),
#'     ToolC = sample(c(0, 1), n_seq, replace = TRUE)
#'   ),
#'   type = sample(c("nc", "cds"), n_seq, replace = TRUE),
#'   isNC = sample(c(0, 1), n_seq, replace = TRUE)
#' )
#'
#' # --- 2. Run the function ---
#' results <- evaluateToolsThresholds(
#'   summaryList = exampleSummaryList,
#'   tools = c("ToolA", "ToolB")
#' )
#'
#' if (!is.null(results)) {
#'   # Accessing the nested list of thresholds
#'   print("Accessing the 'at-least-2' threshold vector:")
#'   print(head(results$atLeastN$atl2))
#' }
#'
evaluateToolsThresholds <- function(summaryList, tools = NULL) {
    # --- 1. Input Validation ---
    stopifnot(
        "'summaryList' must be a list" = is.list(summaryList),
        "'summaryList' must contain required elements" =
            all(c("seqIDs", "tools", "isNC", "type") %in% names(summaryList))
    )
    
    available_tools <- names(summaryList$tools)
    if (length(available_tools) == 0) {
        warning("No tool predictions found in 'summaryList$tools'.", call. = FALSE)
        return(NULL)
    }
    
    # --- 2. Tool Selection (using the central helper function) ---
    selected_tools <- handleToolSelection(
        availableTools = available_tools,
        selectedTools = tools
    )
    
    if (length(selected_tools) == 0) {
        return(NULL) # Helper already issued a warning
    }
    
    # --- 3. Core Calculation ---
    selected_predictions_list <- summaryList$tools[selected_tools]
    
    n_seqs <- length(summaryList$seqIDs)
    predictions_matrix <- do.call(cbind, selected_predictions_list)
    
    if (nrow(predictions_matrix) != n_seqs) {
        warning("Dimension mismatch after combining tool predictions. Aborting.",
                call. = FALSE)
        return(NULL)
    }
    
    sums_selected <- rowSums(predictions_matrix, na.rm = TRUE)
    
    # Calculate "at least n" indicators
    agreement_thresholds <- list()
    num_selected <- length(selected_tools)
    if (num_selected > 0) {
        for (n in seq_len(num_selected)) {
            agreement_thresholds[[paste0('atl', n)]] <-
                as.integer(sums_selected >= n)
        }
    }
    
    # --- 4. Assemble Output List ---
    final_list <- list(
        seqIDs = summaryList$seqIDs,
        isNC = summaryList$isNC,
        type = summaryList$type,
        selectedToolsPredictions = selected_predictions_list,
        sumsSelectedTools = as.integer(sums_selected),
        # ZMIANA: Zagnieżdżenie progów w liście o opisowej nazwie
        atLeastN = agreement_thresholds
    )
    
    return(final_list)
}