#' Create Fourfold Plots for Confusion Matrices
#'
#' Generates fourfold plots to visualize the confusion matrix (TP, TN, FP, FN)
#' for selected methods. Provides a clear, intuitive visual representation of 
#' prediction accuracy and error distribution.
#'
#' @param cmList A named list where each element represents a confusion matrix,
#'   typically the output from `calculateCM`. Must contain `$table`.
#' @param methods An optional character vector of method names to include.
#'   If `NULL`, interactive selection is triggered in an interactive session.
#' @param plotTitle The base title for the plot(s).
#' @param colors A vector of two colors. The first color is for the false
#'   diagonal (errors: FP, FN), and the second is for the true diagonal
#'   (correct predictions: TP, TN). Defaults to pastel red and green.
#' @param conf.level Confidence level for the rings. Set to `0` (default)
#'   to hide the rings for a cleaner presentation on slides/reports.
#' @param std Character string specifying how to standardize the table.
#'   Defaults to `"margins"`.
#' @param ... Additional arguments passed to `graphics::fourfoldplot`.
#'
#' @return This function is called for its side effect of generating plots and
#'   does not return a value (`invisible(NULL)`).
#' @export
#' @importFrom graphics fourfoldplot par
#'
#' @examples
#' # --- Assuming 'allCms' is generated by calculateCM ---
#' # Example 1: Interactive selection (if run in console)
#' # plotFourfoldCm(cmList = allCms)
#' 
#' # Example 2: Plot specific combinations on a grid
#' # plotFourfoldCm(cmList = allCms, methods = c("CPC2+PLEK", "PLEK+CPAT+CNCI"))
#'
plotFourfoldCm <- function(cmList, methods = NULL,
                           plotTitle = "Fourfold Plot of Confusion Matrix",
                           colors = c("#cc6666", "#99cc99"),
                           conf.level = 0,
                           std = "margins", ...) {
  
  # --- 1. Validation and Method Selection ---
  if (!is.list(cmList) || is.null(names(cmList))) {
    stop("'cmList' must be a named list containing confusion matrix results.")
  }
  
  # Use the package's internal selection handler
  selectedMethods <- handleToolSelection(
    availableTools = names(cmList),
    selectedTools = methods
  )
  
  if (length(selectedMethods) == 0) return(invisible(NULL))
  
  # --- 2. Extract Data directly into a 3D Array ---
  # Get dimension names from the first valid table
  first_tbl <- cmList[[selectedMethods[1]]]$table
  if (is.null(first_tbl)) stop(paste("Missing '$table' in method:", selectedMethods[1]))
  
  arr3d <- array(
    dim = c(2, 2, length(selectedMethods)),
    dimnames = list(
      Prediction = rownames(first_tbl),
      Reference = colnames(first_tbl),
      Method = selectedMethods
    )
  )
  
  for (i in seq_along(selectedMethods)) {
    tbl <- cmList[[selectedMethods[i]]]$table
    if (is.null(tbl)) stop(paste("Missing '$table' in method:", selectedMethods[i]))
    arr3d[, , i] <- as.table(tbl)
  }
  
  # --- 3. Native Plotting Logic ---
  # base R natively tiles 3D arrays and labels them using the 'Method' dimnames
  graphics::fourfoldplot(
    arr3d,
    color = colors,
    conf.level = conf.level,
    std = std,
    main = plotTitle,
    ...
  )
  
  return(invisible(NULL))
}